//go:build linux

package native

import (
	"bytes"
	"errors"
	"time"

	"github.com/jezek/xgb"
	"github.com/jezek/xgb/xproto"

	"github.com/wow-look-at-my/competent-search-thing/internal/launch"
)

// serverTimeWait bounds how long serverTime waits for its
// PropertyNotify; the event is generated by the request we just
// completed, so this is only insurance against a wedged server.
const serverTimeWait = time.Second

// WatchState reads one raise-watcher poll over a conn-per-call X
// connection: the EWMH client windows in STACKING order (bottom to
// top, from _NET_CLIENT_LIST_STACKING, falling back to
// _NET_CLIENT_LIST on non-EWMH-stacking WMs), the active window, and
// per window the identity properties the watcher matches on
// (_NET_WM_PID, WM_CLASS instance+class, _NET_STARTUP_ID,
// _NET_WM_USER_TIME). ok=false when there is no X server or no
// client list; the watcher then gives up quietly.
func WatchState() (launch.XState, bool) {
	conn, err := xgb.NewConn()
	if err != nil {
		return launch.XState{}, false
	}
	defer conn.Close()

	root := xproto.Setup(conn).DefaultScreen(conn).Root
	list := windowProp(conn, root, internAtom(conn, "_NET_CLIENT_LIST_STACKING"))
	if list == nil {
		list = windowProp(conn, root, internAtom(conn, "_NET_CLIENT_LIST"))
	}
	if list == nil {
		return launch.XState{}, false
	}
	var st launch.XState
	if v := windowProp(conn, root, internAtom(conn, "_NET_ACTIVE_WINDOW")); len(v) >= 4 {
		st.Active = xgb.Get32(v)
	}
	pidAtom := internAtom(conn, "_NET_WM_PID")
	startupAtom := internAtom(conn, "_NET_STARTUP_ID")
	userTimeAtom := internAtom(conn, "_NET_WM_USER_TIME")
	for i := 0; i+4 <= len(list) && len(st.Windows) < maxOpenWindows; i += 4 {
		win := xproto.Window(xgb.Get32(list[i:]))
		if win == 0 {
			continue
		}
		w := launch.XWindow{ID: uint32(win)}
		if v := windowProp(conn, win, pidAtom); len(v) >= 4 {
			w.PID = int(xgb.Get32(v))
		}
		if parts := bytes.SplitN(windowProp(conn, win, xproto.AtomWmClass), []byte{0}, 3); len(parts) >= 2 {
			w.Instance, w.Class = string(parts[0]), string(parts[1])
		}
		if v := windowProp(conn, win, startupAtom); len(v) > 0 {
			w.StartupID = propString(v)
		}
		if v := windowProp(conn, win, userTimeAtom); len(v) >= 4 {
			w.UserTime = xgb.Get32(v)
		}
		st.Windows = append(st.Windows, w)
	}
	return st, true
}

// internAtomAlways interns name, CREATING the atom when absent --
// scratch property atoms and the startup-info message types must
// exist to be used, while internAtom's only_if_exists probe would
// return 0 for them on a fresh server.
func internAtomAlways(conn *xgb.Conn, name string) xproto.Atom {
	rep, err := xproto.InternAtom(conn, false, uint16(len(name)), name).Reply()
	if err != nil || rep == nil {
		return 0
	}
	return rep.Atom
}

// scratchWindow creates a never-mapped 1x1 InputOnly child of root
// with PropertyChange selected: the owned window serverTime needs for
// its timestamp trick and the sender identity for the SN broadcast.
// It lives until the connection closes.
func scratchWindow(conn *xgb.Conn, root xproto.Window) (xproto.Window, error) {
	wid, err := xproto.NewWindowId(conn)
	if err != nil {
		return 0, err
	}
	err = xproto.CreateWindowChecked(conn, 0 /* depth: CopyFromParent */, wid, root,
		-100, -100, 1, 1, 0, xproto.WindowClassInputOnly, 0, /* visual: CopyFromParent */
		xproto.CwEventMask, []uint32{xproto.EventMaskPropertyChange}).Check()
	if err != nil {
		return 0, err
	}
	return wid, nil
}

// serverTime fetches the X server's CURRENT time with the classic
// zero-length property-append trick (what gdk_x11_get_server_time
// does): append nothing to a scratch property of win -- a window this
// connection owns with PropertyChange selected -- and read the server
// timestamp off the resulting PropertyNotify. 0 on any failure; the
// caller degrades to the old zero-timestamp behavior.
func serverTime(conn *xgb.Conn, win xproto.Window) uint32 {
	atom := internAtomAlways(conn, "_COMPETENT_SEARCH_TIMESTAMP")
	if atom == 0 {
		return 0
	}
	err := xproto.ChangePropertyChecked(conn, xproto.PropModeAppend, win, atom,
		xproto.AtomString, 8, 0, []byte{}).Check()
	if err != nil {
		return 0
	}
	// The notify was generated before the ChangeProperty round-trip
	// completed, so it is normally already queued.
	deadline := time.Now().Add(serverTimeWait)
	for time.Now().Before(deadline) {
		ev, xerr := conn.PollForEvent()
		if ev == nil && xerr == nil {
			time.Sleep(2 * time.Millisecond)
			continue
		}
		if pn, ok := ev.(xproto.PropertyNotifyEvent); ok && pn.Window == win && pn.Atom == atom {
			return uint32(pn.Time)
		}
	}
	return 0
}

// RemoveStartupSequence broadcasts the libstartup-notification
// "remove:" message that ends startup sequence id: ClientMessages to
// the root window -- the first chunk typed _NET_STARTUP_INFO_BEGIN,
// the rest _NET_STARTUP_INFO, format 8, 20 payload bytes each, sent
// with PropertyChange in the event mask from a scratch window that
// identifies the sequence source -- the exact wire form GDK's own
// libsn broadcast uses. Reaping the sequence ourselves matters for
// launchees that never complete startup notification (chromium-family
// apps): without it the busy cursor lives until mutter's 15s timeout.
func RemoveStartupSequence(id string) error {
	conn, err := xgb.NewConn()
	if err != nil {
		return err
	}
	defer conn.Close()

	root := xproto.Setup(conn).DefaultScreen(conn).Root
	begin := internAtomAlways(conn, "_NET_STARTUP_INFO_BEGIN")
	rest := internAtomAlways(conn, "_NET_STARTUP_INFO")
	if begin == 0 || rest == 0 {
		return errors.New("could not intern the startup-info atoms")
	}
	sender, err := scratchWindow(conn, root)
	if err != nil {
		return err
	}
	for i, chunk := range launch.SNChunks(launch.SNRemoveMessage(id)) {
		typ := rest
		if i == 0 {
			typ = begin
		}
		ev := xproto.ClientMessageEvent{
			Format: 8,
			Window: sender,
			Type:   typ,
			Data:   xproto.ClientMessageDataUnionData8New(chunk),
		}
		err := xproto.SendEventChecked(conn, false, root,
			xproto.EventMaskPropertyChange, string(ev.Bytes())).Check()
		if err != nil {
			return err
		}
	}
	return nil
}
