#!/usr/bin/env node
// convert.mjs -- regenerates internal/icons/material/{svg/,mapping.json}
// from a checkout of material-extensions/vscode-material-icon-theme at
// the pinned commit recorded in ../README.md.
//
// Usage:
//   node convert.mjs <upstream-checkout> <material-dir>
//
// What it does (mirroring the upstream generator's semantics at the
// pinned commit -- src/core/generator/fileGenerator.ts):
//   1. Evaluates src/core/icons/fileIcons.ts (imports stripped, the
//      enum/pattern helpers below stand in for the upstream modules;
//      unknown enum members throw so upstream drift fails loudly).
//   2. Filters entries by icon pack exactly like disableIconsByPack
//      with the upstream default activeIconPack "angular": entries
//      with no enabledFor always apply, entries with enabledFor apply
//      only when it lists "angular".
//   3. Skips clone entries (their SVGs are generated by the upstream
//      build via recoloring and are NOT committed in icons/) and any
//      entry whose SVG file is missing.
//   4. Builds fileExtensions/fileNames -> icon-name maps in array
//      order, last entry wins (upstream mapSpecificFileIcons assigns
//      in order). Keys are lowercased; fileNames containing "/" (the
//      cosmiconfig ".config/..." forms) are dropped -- the resolver
//      matches basenames only.
//   5. Generates the default file.svg and folder.svg the same way the
//      upstream build does (generateFileIcons/generateFolderIcons):
//      the path constants extracted from fileGenerator.ts and
//      folderGenerator.ts rendered at the default color from
//      package.json, at the default opacity/saturation 1 (no-ops).
//   6. Copies only REACHABLE SVGs (mapping values + defaults + the
//      _light variants of light-flagged mapped names) into svg/,
//      verifying each is pure ASCII, comment-free, script-free and
//      free of external references.
//   7. Writes mapping.json: sorted keys, 2-space indent, non-ASCII
//      characters \u-escaped so the file bytes stay pure ASCII.

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const [, , upstream, outDir] = process.argv;
if (!upstream || !outDir) {
  console.error("usage: node convert.mjs <upstream-checkout> <material-dir>");
  process.exit(2);
}

// The upstream default icon pack (package.json
// "material-icon-theme.activeIconPack" default).
const ACTIVE_PACK = "angular";

// Enum values mirrored from src/core/models/icons/iconPack.ts and
// src/core/models/icons/patterns/patterns.ts at the pinned commit.
// Wrapped in throw-on-unknown proxies: if upstream adds a member the
// conversion fails instead of silently mapping to undefined.
const strict = (name, obj) =>
  new Proxy(obj, {
    get(t, p) {
      if (typeof p === "string" && !(p in t)) {
        throw new Error(`unknown ${name} member: ${p}`);
      }
      return t[p];
    },
  });
const IconPack = strict("IconPack", {
  Angular: "angular",
  Nest: "nest",
  Ngrx: "angular_ngrx",
  React: "react",
  Redux: "react_redux",
  Roblox: "roblox",
  Qwik: "qwik",
  Vue: "vue",
  Vuex: "vue_vuex",
  Bashly: "bashly",
});
const FileNamePattern = strict("FileNamePattern", {
  Ecmascript: "ecmascript",
  Configuration: "configuration",
  NodeEcosystem: "nodeEcosystem",
  Cosmiconfig: "cosmiconfig",
  Yaml: "yaml",
  Dotfile: "dotfile",
});

// Port of src/core/patterns/patterns.ts (pinned commit) -- expands the
// per-entry patterns into concrete fileNames.
const ecmascript = (n) => ["js", "mjs", "cjs", "ts", "mts", "cts"].map((e) => `${n}.${e}`);
const configuration = (n) => ["json", "jsonc", "json5", "yaml", "yml", "toml"].map((e) => `${n}.${e}`);
const nodeEcosystem = (n) => [...ecmascript(n), ...configuration(n)];
function mapPatterns(patterns) {
  return Object.entries(patterns).flatMap(([n, pattern]) => {
    switch (pattern) {
      case "ecmascript":
        return ecmascript(n);
      case "configuration":
        return configuration(n);
      case "nodeEcosystem":
        return nodeEcosystem(n);
      case "cosmiconfig":
        return [
          `.${n}rc`,
          ...nodeEcosystem(`.${n}rc`),
          `.config/${n}rc`,
          ...nodeEcosystem(`.config/${n}rc`),
          ...nodeEcosystem(`${n}.config`),
        ];
      case "yaml":
        return [`${n}.yaml`, `${n}.yml`];
      case "dotfile":
        return [`.${n}`, n];
      default:
        throw new Error(`unhandled pattern: ${pattern}`);
    }
  });
}
function parseByPattern(raw) {
  return raw.map(({ patterns, fileNames = [], ...rest }) => ({
    ...rest,
    fileNames: patterns ? [...mapPatterns(patterns), ...fileNames] : fileNames,
  }));
}

// ---- evaluate fileIcons.ts -------------------------------------------------
const srcPath = path.join(upstream, "src/core/icons/fileIcons.ts");
const src = fs.readFileSync(srcPath, "utf8");
const marker = "export const fileIcons: FileIcons =";
const at = src.indexOf(marker);
if (at < 0) {
  throw new Error(`marker not found in ${srcPath}`);
}
const body = "__result.fileIcons =" + src.slice(at + marker.length);
const __result = {};
vm.runInNewContext(body, { __result, IconPack, FileNamePattern, parseByPattern });
const fileIcons = __result.fileIcons;
if (!fileIcons || fileIcons.defaultIcon.name !== "file" || !Array.isArray(fileIcons.icons)) {
  throw new Error("fileIcons.ts evaluated to an unexpected shape");
}

// ---- build the maps (upstream order, last wins) ----------------------------
const iconsDir = path.join(upstream, "icons");
const hasSVG = (name) => fs.existsSync(path.join(iconsDir, `${name}.svg`));

const fileExtensions = {};
const fileNames = {};
const lightNames = new Set();
const skipped = { pack: 0, clone: 0, missing: 0, slash: 0 };

for (const icon of fileIcons.icons) {
  if (icon.enabledFor && !icon.enabledFor.some((p) => p === ACTIVE_PACK)) {
    skipped.pack++;
    continue;
  }
  if (icon.clone !== undefined) {
    skipped.clone++;
    continue;
  }
  if (!hasSVG(icon.name)) {
    console.error(`skip ${icon.name}: no icons/${icon.name}.svg upstream`);
    skipped.missing++;
    continue;
  }
  const light = icon.light === true && hasSVG(`${icon.name}_light`);
  if (icon.light === true && !light) {
    console.error(`note ${icon.name}: light-flagged but no _light.svg; using the base icon on light`);
  }
  for (const ext of icon.fileExtensions ?? []) {
    fileExtensions[ext.toLowerCase()] = icon.name;
  }
  for (const fn of icon.fileNames ?? []) {
    if (fn.includes("/")) {
      skipped.slash++;
      continue; // ".config/..." forms: the resolver matches basenames only
    }
    fileNames[fn.toLowerCase()] = icon.name;
  }
  if (light) {
    lightNames.add(icon.name);
  }
}

// ---- default file + folder icons (the upstream build's generation) ---------
function extractConst(file, constName) {
  const text = fs.readFileSync(path.join(upstream, file), "utf8");
  const m = text.match(new RegExp(`const ${constName} =\\s*'([^']+)'`));
  if (!m) {
    throw new Error(`const ${constName} not found in ${file}`);
  }
  return m[1];
}
function defaultColor(key) {
  const pkg = fs.readFileSync(path.join(upstream, "package.json"), "utf8");
  const m = pkg.match(new RegExp(`"material-icon-theme\\.${key}\\.color":\\s*\\{[^}]*"default":\\s*"(#[0-9a-fA-F]{6})"`));
  if (!m) {
    throw new Error(`default ${key}.color not found in package.json`);
  }
  return m[1];
}
// getSVG(getPath(d, color)) from src/core/generator/shared/svg.ts.
const renderSVG = (d, color) =>
  `<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="${d}" fill="${color}" /></svg>`;
const defaultFileSVG = renderSVG(extractConst("src/core/generator/fileGenerator.ts", "fileIcon"), defaultColor("files"));
const defaultFolderSVG = renderSVG(extractConst("src/core/generator/folderGenerator.ts", "folderIcon"), defaultColor("folders"));
for (const clash of ["file", "folder"]) {
  if (hasSVG(clash)) {
    throw new Error(`upstream now ships icons/${clash}.svg; drop the local generation`);
  }
}

// ---- copy reachable SVGs ---------------------------------------------------
const reachable = new Set([...Object.values(fileExtensions), ...Object.values(fileNames)]);
// An entry whose every fileName was slash-scoped can be light-flagged
// yet unreachable; the shipped light list covers only shipped icons.
for (const name of [...lightNames]) {
  if (!reachable.has(name)) {
    lightNames.delete(name);
  }
}
const svgOut = path.join(outDir, "svg");
fs.rmSync(svgOut, { recursive: true, force: true });
fs.mkdirSync(svgOut, { recursive: true });

function checkSVG(name, data) {
  for (let i = 0; i < data.length; i++) {
    if (data[i] > 0x7e || (data[i] < 0x20 && data[i] !== 0x0a && data[i] !== 0x09)) {
      throw new Error(`${name}: non-ASCII or control byte at offset ${i}`);
    }
  }
  const text = data.toString("utf8");
  if (text.includes("<!--") || /<script/i.test(text)) {
    throw new Error(`${name}: comment or script element`);
  }
  for (const m of text.matchAll(/href="([^"]*)"/g)) {
    if (!m[1].startsWith("#")) {
      throw new Error(`${name}: external reference ${m[1]}`);
    }
  }
}

let files = [];
for (const name of [...reachable].sort()) {
  files.push(`${name}.svg`);
  if (lightNames.has(name)) {
    files.push(`${name}_light.svg`);
  }
}
let total = 0;
let maxBytes = 0;
for (const f of files) {
  const data = fs.readFileSync(path.join(iconsDir, f));
  checkSVG(f, data);
  fs.writeFileSync(path.join(svgOut, f), data);
  total += data.length;
  maxBytes = Math.max(maxBytes, data.length);
}
for (const [f, svg] of [["file.svg", defaultFileSVG], ["folder.svg", defaultFolderSVG]]) {
  const data = Buffer.from(svg + "\n", "utf8");
  checkSVG(f, data);
  fs.writeFileSync(path.join(svgOut, f), data);
  files.push(f);
  total += data.length;
  maxBytes = Math.max(maxBytes, data.length);
}

// ---- mapping.json ----------------------------------------------------------
const sorted = (obj) => Object.fromEntries(Object.entries(obj).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
const mapping = {
  defaultFile: "file",
  folder: "folder",
  fileExtensions: sorted(fileExtensions),
  fileNames: sorted(fileNames),
  light: [...lightNames].sort(),
};
const json =
  JSON.stringify(mapping, null, 2).replace(
    /[\u0080-\uffff]/g,
    (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"),
  ) + "\n";
fs.writeFileSync(path.join(outDir, "mapping.json"), json, "ascii");

console.log(
  `converted: ${files.length} svgs (${total} bytes, max ${maxBytes}), ` +
    `${Object.keys(fileExtensions).length} extensions, ` +
    `${Object.keys(fileNames).length} file names, ` +
    `${lightNames.size} light variants; skipped: ` +
    `${skipped.pack} other-pack, ${skipped.clone} clones, ` +
    `${skipped.missing} missing svgs, ${skipped.slash} slash file names`,
);
