// Per-file-type icon resolution for the result rows, over the
// vendored file-icons/atom pack (data.json, generated by
// tools/convert.mjs from the pack's config.cson + LESS -- see
// README.md in this directory). Everything here is SYNCHRONOUS and
// pure: render.ts asks fileIcon(name, isDir) per row and gets the
// glyph character, its icon-font CSS class, and the pack's dark/light
// colour pair back immediately -- no IPC, no Go round-trip, no async
// swap-in. The glyphs render through the four icon fonts fileicons.css
// declares (@font-face over the committed woff2 files).
//
// Matching semantics are the pack's own (ported + verified in
// convert.mjs): rules are pre-sorted by the pack's priority (desc,
// then source order), so the FIRST matching rule in array order wins
// -- special-filename rules (webpack.config.js, Makefile, ...) sit
// ahead of the generic extension rules. A string rule is a
// case-insensitive basename SUFFIX; a regex rule tests the RAW
// basename with its authored flags. No rule matching = the pack's
// defaults (octicons file-text / file-directory), uncolored so the
// theme's fg-dim applies.

import "./fileicons.css";
import data from "./data.json";

// FileIcon is one resolved row icon: the glyph to render, the
// fileicons.css font class ("fi" | "fa" | "mf" | "oct"), and the
// pack's colour pair (absent = theme fg-dim). colorDark/colorLight
// are the pack's per-motif variants; the html.icons-light class
// (toggled by theme.ts via isLightBackground) selects which one the
// CSS consumes.
export interface FileIcon {
  font: string;
  glyph: string;
  colorDark?: string;
  colorLight?: string;
}

// RawRule is data.json's wire shape: i = [fontClass, codepoint],
// r/f = regex source + flags, s = lowercase suffix, c = [dark, light]
// hex colours. Exactly one of r/s is present per rule.
interface RawRule {
  i: [string, number];
  r?: string;
  f?: string;
  s?: string;
  c?: [string, string];
}

interface Rule {
  icon: FileIcon;
  test(name: string, lower: string): boolean;
}

function iconOf(i: [string, number], c?: [string, string]): FileIcon {
  const icon: FileIcon = { font: i[0], glyph: String.fromCodePoint(i[1]) };
  if (c !== undefined) {
    icon.colorDark = c[0];
    icon.colorLight = c[1];
  }
  return icon;
}

function compileRules(raw: RawRule[]): Rule[] {
  const out: Rule[] = [];
  for (const r of raw) {
    const icon = iconOf(r.i, r.c);
    if (r.s !== undefined) {
      const suffix = r.s.toLowerCase();
      out.push({ icon, test: (_name, lower) => lower.endsWith(suffix) });
    } else if (r.r !== undefined) {
      let re: RegExp;
      try {
        // Strip a stray "g" flag: RegExp.test with /g is stateful
        // (lastIndex) and would alternate hits on repeated calls.
        re = new RegExp(r.r, (r.f ?? "").replace(/g/g, ""));
      } catch {
        continue; // defensive: convert.mjs pre-validates every rule
      }
      out.push({ icon, test: (name) => re.test(name) });
    }
  }
  return out;
}

const fileRules = compileRules(data.fileRules as RawRule[]);
const dirRules = compileRules(data.dirRules as RawRule[]);
const defFile = iconOf(data.defFile as [string, number]);
const defDir = iconOf(data.defDir as [string, number]);

// Resolutions memoized per (kind, name); FileIcon values are shared
// and treated as immutable by every consumer. Crude bound like
// render.ts's icon URI cache: a long session's distinct names stay
// finite.
const cache = new Map<string, FileIcon>();
const cacheMax = 4096;

// fileIcon resolves one row's icon. Pure and synchronous; never
// throws; unknown names get the pack's defaults.
export function fileIcon(name: string, isDir: boolean): FileIcon {
  const key = (isDir ? "d:" : "f:") + name;
  const hit = cache.get(key);
  if (hit !== undefined) {
    return hit;
  }
  const rules = isDir ? dirRules : fileRules;
  const lower = name.toLowerCase();
  let icon = isDir ? defDir : defFile;
  for (const r of rules) {
    if (r.test(name, lower)) {
      icon = r.icon;
      break;
    }
  }
  if (cache.size >= cacheMax) {
    cache.clear();
  }
  cache.set(key, icon);
  return icon;
}

/* --- light/dark motif selection ------------------------------------ */

// cssLightness parses a CSS color into its HSL lightness in [0, 1],
// or null when the value is not a recognized color form. Handles the
// forms internal/theme's validator admits for bg: #rgb[a]/#rrggbb[aa]
// hex, rgb()/rgba() numeric (plain or %), hsl()/hsla() (lightness =
// the third component).
function cssLightness(value: string): number | null {
  const v = value.trim().toLowerCase();
  const hex = /^#([0-9a-f]{3,8})$/.exec(v);
  if (hex !== null) {
    const h = hex[1];
    let r: number;
    let g: number;
    let b: number;
    if (h.length === 3 || h.length === 4) {
      r = parseInt(h[0] + h[0], 16);
      g = parseInt(h[1] + h[1], 16);
      b = parseInt(h[2] + h[2], 16);
    } else if (h.length === 6 || h.length === 8) {
      r = parseInt(h.slice(0, 2), 16);
      g = parseInt(h.slice(2, 4), 16);
      b = parseInt(h.slice(4, 6), 16);
    } else {
      return null;
    }
    return (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
  }
  const fn = /^(rgba?|hsla?)\(([^)]*)\)$/.exec(v);
  if (fn === null) {
    return null;
  }
  const parts = fn[2].split(/[\s,/]+/).filter((p) => p !== "");
  if (parts.length < 3) {
    return null;
  }
  if (fn[1].startsWith("hsl")) {
    const l = parseFloat(parts[2]);
    return Number.isFinite(l) ? Math.min(Math.max(l / 100, 0), 1) : null;
  }
  const chan = (p: string): number => {
    const n = parseFloat(p);
    if (!Number.isFinite(n)) {
      return NaN;
    }
    return p.endsWith("%") ? (n * 255) / 100 : n;
  };
  const r = chan(parts[0]);
  const g = chan(parts[1]);
  const b = chan(parts[2]);
  if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) {
    return null;
  }
  return (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
}

// isLightBackground reports whether a CSS background color reads as a
// LIGHT motif -- the file-icons pack's own rule (UI.checkMotif):
// HSL lightness >= 0.5. Unparseable values report false (dark, the
// safe default). theme.ts toggles html.icons-light with this so
// fileicons.css picks each icon's light-theme colour variant.
export function isLightBackground(value: string): boolean {
  const l = cssLightness(value);
  return l !== null && l >= 0.5;
}
