// Per-file-type icon resolution for the result rows, over the
// vendored file-icons/atom pack. The mapping artifact is data.bin --
// a compact binpazer container (wow-look-at-my/bin-file-fmt)
// generated by tools/convert.mjs and committed at
// internal/fileicons/data.bin, where the Go side embeds it and
// decodes it through the format's first-party reader. The frontend
// fetches the DECODED table once at wire-up (initFileIcons over the
// GetFileIcons bound method) and compiles it here; until the answer
// lands -- and whenever the artifact cannot be decoded -- the
// matcher serves the pack's uncolored octicon defaults, so file rows
// always render.
//
// fileIcon(name, isDir) itself stays SYNCHRONOUS and pure: render.ts
// asks per row and gets the glyph character, its icon-font CSS class
// ("fi" | "fa" | "mf" | "oct" | "di" -- fileicons.css's @font-face
// classes over the committed woff2 files), and the pack's dark/light
// colour pair back immediately. installFileIcons clears the memo cache, so
// rows resolved before the table landed self-correct on their next
// render.
//
// Matching semantics are the pack's own (ported + verified in
// convert.mjs): rules are pre-sorted by the pack's priority (desc,
// then source order), so the FIRST matching rule in array order wins
// -- special-filename rules (webpack.config.js, Makefile, ...) sit
// ahead of the generic extension rules. A string rule is a
// case-insensitive basename SUFFIX; a regex rule tests the RAW
// basename with its authored flags. No rule matching = the pack's
// defaults (octicons file-text / file-directory), uncolored so the
// theme's fg-dim applies.

import "./fileicons.css";

// FileIcon is one resolved row icon: the glyph to render, the
// fileicons.css font class, and the pack's colour pair (absent =
// theme fg-dim). colorDark/colorLight are the pack's per-motif
// variants; the html.icons-light class (toggled by theme.ts via
// isLightBackground) selects which one the CSS consumes.
export interface FileIcon {
  font: string;
  glyph: string;
  colorDark?: string;
  colorLight?: string;
}

interface Rule {
  icon: FileIcon;
  test(name: string, lower: string): boolean;
}

// The pack's uncolored fallback glyphs (octicons file-text and
// file-directory) -- what the matcher serves before the table lands
// and when the Go side degraded. Kept lockstep with
// internal/fileicons' fallback constants.
const fallbackFile: FileIcon = { font: "oct", glyph: String.fromCodePoint(0xf011) };
const fallbackDir: FileIcon = { font: "oct", glyph: String.fromCodePoint(0xf016) };

let fileRules: Rule[] = [];
let dirRules: Rule[] = [];
let defFile: FileIcon = fallbackFile;
let defDir: FileIcon = fallbackDir;

function validIcon(i: FileIconsIcon | undefined): boolean {
  return (
    i !== undefined &&
    typeof i.font === "string" &&
    i.font !== "" &&
    Number.isInteger(i.cp) &&
    i.cp > 0 &&
    i.cp <= 0x10ffff
  );
}

function iconOf(i: FileIconsIcon, dark?: string, light?: string): FileIcon {
  const icon: FileIcon = { font: i.font, glyph: String.fromCodePoint(i.cp) };
  if (dark !== undefined && light !== undefined) {
    icon.colorDark = dark;
    icon.colorLight = light;
  }
  return icon;
}

function compileRules(raw: FileIconsRule[]): Rule[] {
  const out: Rule[] = [];
  for (const r of raw) {
    if (!validIcon(r)) {
      continue; // defensive: the Go decoder validates all of this
    }
    const icon = iconOf(r, r.dark, r.light);
    if (r.suffix !== undefined && r.suffix !== "") {
      const suffix = r.suffix.toLowerCase();
      out.push({ icon, test: (_name, lower) => lower.endsWith(suffix) });
    } else if (r.regex !== undefined && r.regex !== "") {
      let re: RegExp;
      try {
        // Strip a stray "g" flag: RegExp.test with /g is stateful
        // (lastIndex) and would alternate hits on repeated calls.
        re = new RegExp(r.regex, (r.flags ?? "").replace(/g/g, ""));
      } catch {
        continue; // defensive: convert.mjs pre-validates every rule
      }
      out.push({ icon, test: (name) => re.test(name) });
    }
  }
  return out;
}

// installFileIcons swaps the wire table in (compiling the rules) and
// clears the memo cache. A table whose defaults are malformed is
// refused whole -- the current tables (at worst the pack fallbacks)
// stay -- so a broken bridge answer costs icons, never the bar.
export function installFileIcons(t: FileIconsTable | null | undefined): void {
  if (t === null || t === undefined || !validIcon(t.defFile) || !validIcon(t.defDir)) {
    console.warn("fileicons: refusing a malformed icon table");
    return;
  }
  fileRules = compileRules(t.fileRules ?? []);
  dirRules = compileRules(t.dirRules ?? []);
  defFile = iconOf(t.defFile);
  defDir = iconOf(t.defDir);
  cache.clear();
}

// initFileIcons fetches the table once (called from wire(), the
// initTheme pattern: fire-and-forget -- the bar starts hidden, so
// the answer is installed long before the first file row renders).
export async function initFileIcons(app: WailsAppBindings): Promise<void> {
  try {
    installFileIcons(await app.GetFileIcons());
  } catch (err: unknown) {
    console.warn("fileicons: table fetch failed: " + String(err));
  }
}

// Resolutions memoized per (kind, name); FileIcon values are shared
// and treated as immutable by every consumer. Crude bound like
// render.ts's icon URI cache: a long session's distinct names stay
// finite.
const cache = new Map<string, FileIcon>();
const cacheMax = 4096;

// fileIcon resolves one row's icon. Pure and synchronous; never
// throws; unknown names get the pack's defaults.
export function fileIcon(name: string, isDir: boolean): FileIcon {
  const key = (isDir ? "d:" : "f:") + name;
  const hit = cache.get(key);
  if (hit !== undefined) {
    return hit;
  }
  const rules = isDir ? dirRules : fileRules;
  const lower = name.toLowerCase();
  let icon = isDir ? defDir : defFile;
  for (const r of rules) {
    if (r.test(name, lower)) {
      icon = r.icon;
      break;
    }
  }
  if (cache.size >= cacheMax) {
    cache.clear();
  }
  cache.set(key, icon);
  return icon;
}

/* --- light/dark motif selection ------------------------------------ */

// cssLightness parses a CSS color into its HSL lightness in [0, 1],
// or null when the value is not a recognized color form. Handles the
// forms internal/theme's validator admits for bg: #rgb[a]/#rrggbb[aa]
// hex, rgb()/rgba() numeric (plain or %), hsl()/hsla() (lightness =
// the third component).
function cssLightness(value: string): number | null {
  const v = value.trim().toLowerCase();
  const hex = /^#([0-9a-f]{3,8})$/.exec(v);
  if (hex !== null) {
    const h = hex[1];
    let r: number;
    let g: number;
    let b: number;
    if (h.length === 3 || h.length === 4) {
      r = parseInt(h[0] + h[0], 16);
      g = parseInt(h[1] + h[1], 16);
      b = parseInt(h[2] + h[2], 16);
    } else if (h.length === 6 || h.length === 8) {
      r = parseInt(h.slice(0, 2), 16);
      g = parseInt(h.slice(2, 4), 16);
      b = parseInt(h.slice(4, 6), 16);
    } else {
      return null;
    }
    return (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
  }
  const fn = /^(rgba?|hsla?)\(([^)]*)\)$/.exec(v);
  if (fn === null) {
    return null;
  }
  const parts = fn[2].split(/[\s,/]+/).filter((p) => p !== "");
  if (parts.length < 3) {
    return null;
  }
  if (fn[1].startsWith("hsl")) {
    const l = parseFloat(parts[2]);
    return Number.isFinite(l) ? Math.min(Math.max(l / 100, 0), 1) : null;
  }
  const chan = (p: string): number => {
    const n = parseFloat(p);
    if (!Number.isFinite(n)) {
      return NaN;
    }
    return p.endsWith("%") ? (n * 255) / 100 : n;
  };
  const r = chan(parts[0]);
  const g = chan(parts[1]);
  const b = chan(parts[2]);
  if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) {
    return null;
  }
  return (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
}

// isLightBackground reports whether a CSS background color reads as a
// LIGHT motif -- the file-icons pack's own rule (UI.checkMotif):
// HSL lightness >= 0.5. Unparseable values report false (dark, the
// safe default). theme.ts toggles html.icons-light with this so
// fileicons.css picks each icon's light-theme colour variant.
export function isLightBackground(value: string): boolean {
  const l = cssLightness(value);
  return l !== null && l >= 0.5;
}
