package ffext

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// hostDescription is the native manifest's description field.
const hostDescription = "competent-search-thing Firefox tab-activation bridge"

// nativeManifest is the JSON shape Firefox reads from the
// native-messaging host manifest (MDN Native_manifests: name,
// description, path, type "stdio", allowed_extensions).
type nativeManifest struct {
	Name              string   `json:"name"`
	Description       string   `json:"description"`
	Path              string   `json:"path"`
	Type              string   `json:"type"`
	AllowedExtensions []string `json:"allowed_extensions"`
}

// ManifestPath returns where the native-messaging host manifest lives
// for the user-level install, per Firefox's documented locations:
// linux (and other unix-likes) ~/.mozilla/native-messaging-hosts/,
// darwin ~/Library/Application Support/Mozilla/NativeMessagingHosts/.
// On windows the JSON file can live anywhere (the registry key points
// at it), so it goes in the app's own config directory. ok=false when
// the needed base (home / configDir) is unknown; callers degrade.
func ManifestPath(goos, home, configDir string) (string, bool) {
	switch goos {
	case "windows":
		if configDir == "" {
			return "", false
		}
		return filepath.Join(configDir, HostName+".json"), true
	case "darwin":
		if home == "" {
			return "", false
		}
		return filepath.Join(home, "Library", "Application Support", "Mozilla", "NativeMessagingHosts", HostName+".json"), true
	default:
		if home == "" {
			return "", false
		}
		return filepath.Join(home, ".mozilla", "native-messaging-hosts", HostName+".json"), true
	}
}

// WrapperPath returns the generated host wrapper's path inside the
// app's config directory: a shell script on unix-likes, a batch file
// on windows (Firefox executes the manifest's path directly, and a
// bare "binary + subcommand argv" cannot be expressed there).
func WrapperPath(goos, configDir string) string {
	if goos == "windows" {
		return filepath.Join(configDir, "firefox-host.bat")
	}
	return filepath.Join(configDir, "firefox-host.sh")
}

// wrapperExeRe extracts the executable a generated wrapper points at,
// for the self-heal repair log: the single-quoted sh spelling or the
// double-quoted bat spelling.
var wrapperExeRe = regexp.MustCompile(`(?m)^exec '((?:[^']|'\\'')*)' firefox-host|^"([^"]+)" firefox-host`)

// WrapperContent renders the host wrapper for goos around exe (the
// stable spelling of the app binary). Firefox appends its own
// arguments (manifest path, extension id); the wrapper forwards them.
func WrapperContent(goos, exe string) []byte {
	if goos == "windows" {
		return []byte("@echo off\r\n\"" + exe + "\" firefox-host %*\r\n")
	}
	return []byte("#!/bin/sh\n" +
		"# Generated by competent-search-thing; rewritten at every app startup.\n" +
		"exec " + shQuote(exe) + " firefox-host \"$@\"\n")
}

// wrapperExe parses the executable out of an existing wrapper's
// content ("" when it does not look like ours) -- the old half of the
// repaired-old-to-new log line.
func wrapperExe(content []byte) string {
	m := wrapperExeRe.FindSubmatch(content)
	if m == nil {
		return ""
	}
	if len(m[1]) > 0 {
		return strings.ReplaceAll(string(m[1]), `'\''`, `'`)
	}
	return string(m[2])
}

// shQuote single-quotes s for POSIX sh (embedded single quotes become
// the standard '\'' splice).
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, `'`, `'\''`) + "'"
}

// ManifestContent renders the native manifest JSON pointing Firefox at
// wrapperPath (two-space indent + trailing newline, the config.Encode
// convention).
func ManifestContent(wrapperPath string) []byte {
	data, err := json.MarshalIndent(nativeManifest{
		Name:              HostName,
		Description:       hostDescription,
		Path:              wrapperPath,
		Type:              "stdio",
		AllowedExtensions: []string{ExtensionID},
	}, "", "  ")
	if err != nil {
		// A plain struct of strings cannot fail to marshal.
		panic(err)
	}
	return append(data, '\n')
}

// InstallResult reports what InstallHost did, for the app layer's
// logging: which files were (re)written, and -- when an existing
// wrapper pointed at a different executable -- the previous spelling
// for the one loud repaired-old-to-new line (the gsettings self-heal
// precedent).
type InstallResult struct {
	ManifestPath  string
	WrapperPath   string
	WroteWrapper  bool
	WroteManifest bool
	// PreviousExe is the executable an existing wrapper named before
	// this rewrite ("" when the wrapper is new, unchanged, or not
	// parseable as ours).
	PreviousExe string
}

// InstallHost writes (or self-heals) the native-messaging host pieces:
// the wrapper script in configDir and the manifest in Firefox's
// per-OS location (plus, on windows, the HKCU registry value naming
// the manifest). Both writes are atomic (temp-file-then-rename, the
// config.Save shape) and skipped byte-for-byte-unchanged content, so
// a steady-state startup performs two reads and zero writes.
func InstallHost(goos, home, configDir, exe string) (InstallResult, error) {
	var res InstallResult
	mpath, ok := ManifestPath(goos, home, configDir)
	if !ok {
		return res, fmt.Errorf("no native-messaging manifest location for goos %q (home %q, configDir %q)", goos, home, configDir)
	}
	if configDir == "" {
		return res, fmt.Errorf("no config directory for the host wrapper")
	}
	res.ManifestPath = mpath
	res.WrapperPath = WrapperPath(goos, configDir)

	wantWrapper := WrapperContent(goos, exe)
	haveWrapper, err := os.ReadFile(res.WrapperPath)
	switch {
	case err == nil && bytes.Equal(haveWrapper, wantWrapper):
		// Unchanged; keep the exec bit honest anyway (cheap, and a
		// copied-in wrapper may have lost it).
		if goos != "windows" {
			_ = os.Chmod(res.WrapperPath, 0o700)
		}
	default:
		if err == nil {
			res.PreviousExe = wrapperExe(haveWrapper)
			if res.PreviousExe == exe {
				res.PreviousExe = ""
			}
		}
		perm := os.FileMode(0o700)
		if goos == "windows" {
			perm = 0o755
		}
		if werr := writeFileAtomic(res.WrapperPath, wantWrapper, perm); werr != nil {
			return res, fmt.Errorf("write host wrapper: %w", werr)
		}
		res.WroteWrapper = true
	}

	wantManifest := ManifestContent(res.WrapperPath)
	haveManifest, err := os.ReadFile(mpath)
	if err != nil || !bytes.Equal(haveManifest, wantManifest) {
		if werr := writeFileAtomic(mpath, wantManifest, 0o644); werr != nil {
			return res, fmt.Errorf("write native manifest: %w", werr)
		}
		res.WroteManifest = true
	}

	if goos == "windows" {
		if rerr := registerHostManifest(mpath); rerr != nil {
			return res, fmt.Errorf("register native manifest: %w", rerr)
		}
	}
	return res, nil
}

// writeFileAtomic writes data to path via a temp file in the same
// directory and one rename (the config.Save shape): a crash never
// leaves a truncated file, and watchers see exactly one change.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".ffext-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	cleanup := func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}
	if _, err := tmp.Write(data); err != nil {
		cleanup()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}
