package service

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSystemdUnitGolden(t *testing.T) {
	got := SystemdUnit("/usr/local/bin/competent-search-thing")
	want := `# competent-search-thing user service (generated by 'competent-search-thing service install')
[Unit]
Description=competent-search-thing Spotlight-style searchbar
Documentation=https://github.com/wow-look-at-my/competent-search-thing
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=exec
ExecStart=/usr/local/bin/competent-search-thing
Restart=on-failure
RestartSec=2

[Install]
WantedBy=graphical-session.target
`
	require.Equal(t, want, got)
}

// TestSystemdUnitCrashOnlyRestart pins Restart=on-failure: the
// service copy that finds another instance running exits 0 through
// the IPC handoff and must NOT be respawn-looped.
func TestSystemdUnitCrashOnlyRestart(t *testing.T) {
	got := SystemdUnit("/bin/app")
	require.Contains(t, got, "Restart=on-failure\n")
	require.NotContains(t, got, "Restart=always", "always would loop the exit-0 handoff")
}

// TestSystemdUnitBindsToGraphicalSession pins the GUI-session
// binding: the app starts with the desktop (which imports the
// display environment into the user manager), not before it.
func TestSystemdUnitBindsToGraphicalSession(t *testing.T) {
	got := SystemdUnit("/bin/app")
	require.Contains(t, got, "WantedBy=graphical-session.target\n")
	require.Contains(t, got, "PartOf=graphical-session.target\n")
	require.Contains(t, got, "After=graphical-session.target\n")
	require.NotContains(t, got, "WantedBy=default.target",
		"default.target would start the GUI app before any display exists")
}

func TestSystemdExecPathEscaping(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"plain", "/usr/bin/app", "/usr/bin/app"},
		{"percent doubled", "/opt/100%tools/app", "/opt/100%%tools/app"},
		{"space quoted", "/opt/my tools/app", `"/opt/my tools/app"`},
		{"quote escaped", `/opt/we"ird/app`, `"/opt/we\"ird/app"`},
		{"backslash escaped", `/opt/back\slash/app`, `"/opt/back\\slash/app"`},
		{"single quote quoted", "/opt/it's/app", `"/opt/it's/app"`},
		{"percent then space", "/opt/100% done/app", `"/opt/100%% done/app"`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			require.Equal(t, tc.want, systemdExecPath(tc.in))
		})
	}
}

func TestSystemdUnitEscapesExecStart(t *testing.T) {
	got := SystemdUnit("/opt/my tools/100%app")
	require.Contains(t, got, "ExecStart=\"/opt/my tools/100%%app\"\n")
	lines := strings.Split(got, "\n")
	var execLines int
	for _, l := range lines {
		if strings.HasPrefix(l, "ExecStart=") {
			execLines++
		}
	}
	require.Equal(t, 1, execLines, "exactly one ExecStart line")
}
