package service

import "strings"

// SystemdUnit renders the systemd user unit for the given binary.
//
// Key choices:
//   - WantedBy/PartOf graphical-session.target: this is a GUI app --
//     it must start WITH the desktop (which imports DISPLAY /
//     WAYLAND_DISPLAY into the user manager), not before the display
//     exists, and stop when the session ends. Requires a desktop that
//     manages graphical-session.target (GNOME, KDE, most modern DEs).
//   - Restart=on-failure: restart on a crash (non-zero exit or
//     signal) ONLY; a clean exit 0 -- the single-instance handoff
//     path when another copy already runs -- must NOT respawn-loop.
//   - RestartSec=2: space genuine crash restarts so a boot-crash
//     does not burn systemd's default start-limit burst instantly.
//   - Type=exec: activation fails loudly if the binary is gone.
//
// Logging deliberately stays with systemd's default: stdout/stderr
// go to the user journal (journalctl --user -u competent-search-thing).
func SystemdUnit(exe string) string {
	return `# ` + appName + ` user service (generated by '` + appName + ` service install')
[Unit]
Description=` + appName + ` Spotlight-style searchbar
Documentation=https://github.com/wow-look-at-my/` + appName + `
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=exec
ExecStart=` + systemdExecPath(exe) + `
Restart=on-failure
RestartSec=2

[Install]
WantedBy=graphical-session.target
`
}

// systemdExecPath renders a binary path for an ExecStart= line: "%"
// is a unit-file specifier character and is always doubled, and a
// path containing whitespace or quote characters is double-quoted
// with systemd's C-style escapes for backslash and double quote.
func systemdExecPath(p string) string {
	p = strings.ReplaceAll(p, "%", "%%")
	if strings.ContainsAny(p, " \t\"'\\") {
		p = `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(p) + `"`
	}
	return p
}
