// Config editor lifecycle over a schema FIXTURE (jsdom; the real
// index.html markup is loaded by test-setup.ts): the ToC sidebar is
// generated by the same walk that renders the controls (schema order,
// sub-entries, the synthetic General group, x-editor-hidden pruning
// on both the property node and its $ref target), the filter dims
// zero-match entries and counts matches, a dimmed entry's click
// clears the filter, and the hide/show cycle RESTORES the editor --
// mode, scroll, focused control, dirty edits -- while Esc/Close still
// exit to a fresh search bar. Tests run in declaration order over ONE
// initConfig (the module wires window listeners once, like the app).

import { beforeAll, describe, expect, it } from "vitest";
import { configModeActive, initConfig, openConfigWindow } from "./config";

const fixtureSchema = {
  properties: {
    $schema: { type: "string", "x-editor-hidden": true },
    alpha: { type: "string", description: "alpha text" },
    beta: { type: "integer", description: "beta number" },
    hiddenLeaf: { type: "string", "x-editor-hidden": true },
    groupa: {
      type: "object",
      description: "group a",
      properties: {
        flag: { type: "boolean", description: "a flag" },
        sub: { $ref: "#/$defs/subDef" },
      },
    },
    secret: { $ref: "#/$defs/hiddenDef" },
    trailing: { type: "string", description: "trailing leaf" },
  },
  $defs: {
    subDef: {
      type: "object",
      properties: { knob: { type: "number", description: "sub knob" } },
    },
    hiddenDef: {
      "x-editor-hidden": true,
      type: "object",
      properties: { x: { type: "string" } },
    },
  },
};

const fixtureDoc = {
  alpha: "hello",
  beta: 2,
  groupa: { flag: true, sub: { knob: 1.5 } },
  trailing: "t",
};

interface FakeEnv {
  app: WailsAppBindings;
  rt: WailsRuntime;
  fire: (name: string, ...data: unknown[]) => void;
  // closes counts CloseConfigWindow calls -- the settings window's
  // Esc / Close outcome.
  closes: number;
}

function fakeEnv(schemaJson: string, configJson: string): FakeEnv {
  const events = new Map<string, (...data: unknown[]) => void>();
  const out: FakeEnv = {
    app: null as unknown as WailsAppBindings,
    rt: null as unknown as WailsRuntime,
    fire: () => {},
    closes: 0,
  };
  const app = {
    CloseConfigWindow: () => {
      out.closes++;
      return Promise.resolve();
    },
    GetConfigSchema: () => Promise.resolve(schemaJson),
    GetConfigForEdit: () =>
      Promise.resolve({ configJson, path: "/tmp/config.json" }),
    SaveConfig: () => Promise.resolve({ ok: true, applied: [], pending: [] }),
    OpenConfigFile: () => Promise.resolve(),
    GetPreviewConfig: () =>
      Promise.resolve({
        enabled: false,
        kagiConfigured: false,
        aiProvider: "openai",
        aiConfigured: false,
        resultsWidth: 680,
      }),
  } as unknown as WailsAppBindings;
  const rt = {
    EventsOn: (name: string, cb: (...data: unknown[]) => void) => {
      events.set(name, cb);
      return () => {};
    },
  } as unknown as WailsRuntime;
  out.app = app;
  out.rt = rt;
  out.fire = (name, ...data) => {
    const cb = events.get(name);
    if (cb === undefined) {
      throw new Error("no handler registered for " + name);
    }
    cb(...data);
  };
  return out;
}

// tick flushes microtasks plus one macrotask turn.
function tick(): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, 0);
  });
}

function byId<T extends HTMLElement>(id: string): T {
  const n = document.getElementById(id);
  if (n === null) {
    throw new Error("missing #" + id);
  }
  return n as T;
}

function tocIds(): string[] {
  return Array.from(
    byId("config-toc").querySelectorAll<HTMLButtonElement>(
      ".config-toc-entry",
    ),
  ).map((b) => b.id.replace(/^config-toc-/, ""));
}

let env: FakeEnv;

beforeAll(() => {
  env = fakeEnv(JSON.stringify(fixtureSchema), JSON.stringify(fixtureDoc));
  initConfig(env.app, env.rt);
});

describe("config editor ToC", () => {
  it("renders ToC entries from the schema walk in schema order", async () => {
    openConfigWindow();
    await tick();
    await tick();
    expect(configModeActive()).toBe(true);
    expect(document.body.classList.contains("with-config")).toBe(true);
    expect(tocIds()).toEqual(["general", "groupa", "groupa.sub", "trailing"]);
    // Sub-entries are marked; top-level ones are not.
    expect(
      byId("config-toc-groupa.sub").classList.contains("config-toc-sub"),
    ).toBe(true);
    expect(byId("config-toc-groupa").classList.contains("config-toc-sub")).toBe(
      false,
    );
    // The synthetic General group collects the leading top-level
    // leaves; the post-section leaf got its own group.
    const general = byId("config-sec-general");
    expect(general.querySelector("#cfg-alpha")).not.toBeNull();
    expect(general.querySelector("#cfg-beta")).not.toBeNull();
    expect(byId("config-sec-trailing").querySelector("#cfg-trailing")).not.toBeNull();
  });

  it("prunes x-editor-hidden leaves and subtrees (property and $ref)", () => {
    expect(document.getElementById("cfg-hiddenLeaf")).toBeNull();
    expect(document.getElementById("config-sec-secret")).toBeNull();
    expect(document.getElementById("cfg-secret-x")).toBeNull();
    expect(document.getElementById("cfg-$schema")).toBeNull();
    expect(tocIds()).not.toContain("secret");
  });

  it("filter dims zero-match entries and counts matches", async () => {
    const filter = byId<HTMLInputElement>("config-filter");
    filter.value = "knob";
    filter.dispatchEvent(new Event("input"));
    await tick();
    // groupa's count is its subtree total (includes the sub-section).
    const count = (id: string): string =>
      byId(id).querySelector(".config-toc-count")?.textContent ?? "";
    const dimmed = (id: string): boolean =>
      byId(id).classList.contains("config-toc-dim");
    expect(dimmed("config-toc-general")).toBe(true);
    expect(dimmed("config-toc-trailing")).toBe(true);
    expect(dimmed("config-toc-groupa")).toBe(false);
    expect(dimmed("config-toc-groupa.sub")).toBe(false);
    expect(count("config-toc-groupa")).toBe("1");
    expect(count("config-toc-groupa.sub")).toBe("1");
    // Zero-match sections are hidden in the controls column.
    expect(byId("config-sec-trailing").hidden).toBe(true);
    // Clearing restores everything.
    filter.value = "";
    filter.dispatchEvent(new Event("input"));
    await tick();
    expect(dimmed("config-toc-general")).toBe(false);
    expect(byId("config-sec-trailing").hidden).toBe(false);
    const c = byId("config-toc-groupa").querySelector<HTMLElement>(
      ".config-toc-count",
    );
    expect(c?.hidden).toBe(true);
  });

  it("clicking a dimmed entry clears the filter and jumps", async () => {
    const filter = byId<HTMLInputElement>("config-filter");
    filter.value = "knob";
    filter.dispatchEvent(new Event("input"));
    await tick();
    expect(byId("config-sec-trailing").hidden).toBe(true);
    byId("config-toc-trailing").click();
    await tick();
    expect(filter.value).toBe("");
    expect(byId("config-sec-trailing").hidden).toBe(false);
  });

  it("offers the reload strip for an external change while dirty", () => {
    // Make the working copy dirty through a real control first.
    const alpha = byId<HTMLInputElement>("cfg-alpha");
    alpha.value = "changed";
    alpha.dispatchEvent(new Event("input"));
    expect(byId("config-dirty-note").hidden).toBe(false);

    env.fire("config:changed", { applied: ["theme"], pending: null });
    const notices = byId("config-notices").textContent ?? "";
    expect(notices).toContain("changed on disk");
    // The dirty working copy is kept, not clobbered.
    expect(byId<HTMLInputElement>("cfg-alpha").value).toBe("changed");
    expect(byId("config-dirty-note").hidden).toBe(false);
  });

  // In the settings window Esc closes the WINDOW (there is no
  // searchbar underneath to fall back to), and a dirty document still
  // takes two presses before anything is discarded.
  it("Esc closes the settings window, dirty double-press first", () => {
    const esc = (): void => {
      window.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));
    };
    esc(); // first press arms the discard warning
    expect(env.closes).toBe(0);
    expect(configModeActive()).toBe(true);
    esc(); // second press within the window discards and closes
    expect(env.closes).toBe(1);
  });
});
